[project]
name = "cfsai-types"
version = "2.0.0"
description = "CFSAI common types to be shared among all packages"
readme = "README.md"
authors = [
    { name = "Codefusion Studio Team", email = "processor.tools.support@analog.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pydantic>=2.11.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
