[project]
name = "cfsai-model-parser"
version = "2.0.0"
description = "This package provides tools for parsing and analyzing machine learning models."
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "cfsai-tflite",
    "numpy==1.26.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cfsai-tflite = { workspace = true }
