[project]
name = "cfsai-compatibility-analyzer"
version = "2.0.0"
description = "This package provides tools for analyzing compatibility of machine learning models with various hardware platforms."
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "cfsai-model-parser",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cfsai-model-parser = { workspace = true }
