[project]
name = "cfsai-tflite"
version = "2.0.0"
description = "Tensorflow lite parsing utilities based on the flatbuffer generated schema"
readme = "README.md"
authors = [
    { name = "Codefusion Studio Team", email = "processor.tools.support@analog.com" }
]
requires-python = ">=3.11"
dependencies = [
    "flatbuffers>=25.2.10",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.hooks.custom]
path = "build_hook.py"

[dependency-groups]
dev = [
    "hatchling>=1.27.0",
]
