[project]
name = "cfsai-resource-profiler"
version = "2.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.9"
dependencies = [
    "cfsai-model-parser",
    "cfsai-tflite",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
cfsai-model-parser = { workspace = true }
cfsai-tflite = { workspace = true }
